# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/invocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs import model_pb2 as protobufs_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotobufs/invocation.proto\x12\rinvocation.v1\x1a\x15protobufs/model.proto\">\n\x11InvocationRequest\x12)\n\x0bmodel_input\x18\x01 \x01(\x0b\x32\x14.model.v1.ModelInput\"5\n\x12InvocationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\nInvocation\x12M\n\x06Invoke\x12 .invocation.v1.InvocationRequest\x1a!.invocation.v1.InvocationResponseb\x06proto3')



_INVOCATIONREQUEST = DESCRIPTOR.message_types_by_name['InvocationRequest']
_INVOCATIONRESPONSE = DESCRIPTOR.message_types_by_name['InvocationResponse']
InvocationRequest = _reflection.GeneratedProtocolMessageType('InvocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONREQUEST,
  '__module__' : 'protobufs.invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.InvocationRequest)
  })
_sym_db.RegisterMessage(InvocationRequest)

InvocationResponse = _reflection.GeneratedProtocolMessageType('InvocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONRESPONSE,
  '__module__' : 'protobufs.invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.InvocationResponse)
  })
_sym_db.RegisterMessage(InvocationResponse)

_INVOCATION = DESCRIPTOR.services_by_name['Invocation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVOCATIONREQUEST._serialized_start=68
  _INVOCATIONREQUEST._serialized_end=130
  _INVOCATIONRESPONSE._serialized_start=132
  _INVOCATIONRESPONSE._serialized_end=185
  _INVOCATION._serialized_start=187
  _INVOCATION._serialized_end=278
# @@protoc_insertion_point(module_scope)
