# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobufs/model.proto\x12\x08model.v1\"0\n\x12ModelInputMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"Y\n\nModelInput\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12.\n\x08metadata\x18\x03 \x03(\x0b\x32\x1c.model.v1.ModelInputMetadata\"1\n\x13ModelOutputMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"J\n\x0bModelOutput\x12\n\n\x02id\x18\x01 \x01(\x05\x12/\n\x08metadata\x18\x02 \x03(\x0b\x32\x1d.model.v1.ModelOutputMetadatab\x06proto3')



_MODELINPUTMETADATA = DESCRIPTOR.message_types_by_name['ModelInputMetadata']
_MODELINPUT = DESCRIPTOR.message_types_by_name['ModelInput']
_MODELOUTPUTMETADATA = DESCRIPTOR.message_types_by_name['ModelOutputMetadata']
_MODELOUTPUT = DESCRIPTOR.message_types_by_name['ModelOutput']
ModelInputMetadata = _reflection.GeneratedProtocolMessageType('ModelInputMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUTMETADATA,
  '__module__' : 'protobufs.model_pb2'
  # @@protoc_insertion_point(class_scope:model.v1.ModelInputMetadata)
  })
_sym_db.RegisterMessage(ModelInputMetadata)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUT,
  '__module__' : 'protobufs.model_pb2'
  # @@protoc_insertion_point(class_scope:model.v1.ModelInput)
  })
_sym_db.RegisterMessage(ModelInput)

ModelOutputMetadata = _reflection.GeneratedProtocolMessageType('ModelOutputMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUTMETADATA,
  '__module__' : 'protobufs.model_pb2'
  # @@protoc_insertion_point(class_scope:model.v1.ModelOutputMetadata)
  })
_sym_db.RegisterMessage(ModelOutputMetadata)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUT,
  '__module__' : 'protobufs.model_pb2'
  # @@protoc_insertion_point(class_scope:model.v1.ModelOutput)
  })
_sym_db.RegisterMessage(ModelOutput)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELINPUTMETADATA._serialized_start=35
  _MODELINPUTMETADATA._serialized_end=83
  _MODELINPUT._serialized_start=85
  _MODELINPUT._serialized_end=174
  _MODELOUTPUTMETADATA._serialized_start=176
  _MODELOUTPUTMETADATA._serialized_end=225
  _MODELOUTPUT._serialized_start=227
  _MODELOUTPUT._serialized_end=301
# @@protoc_insertion_point(module_scope)
