# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10invocation.proto\x12\rinvocation.v1\"0\n\x12ModelInputMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"^\n\nModelInput\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x33\n\x08metadata\x18\x03 \x03(\x0b\x32!.invocation.v1.ModelInputMetadata\"1\n\x13ModelOutputMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"O\n\x0bModelOutput\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x34\n\x08metadata\x18\x02 \x03(\x0b\x32\".invocation.v1.ModelOutputMetadata\"C\n\x11InvocationRequest\x12.\n\x0bmodel_input\x18\x01 \x01(\x0b\x32\x19.invocation.v1.ModelInput\"5\n\x12InvocationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\nInvocation\x12M\n\x06Invoke\x12 .invocation.v1.InvocationRequest\x1a!.invocation.v1.InvocationResponseb\x06proto3')



_MODELINPUTMETADATA = DESCRIPTOR.message_types_by_name['ModelInputMetadata']
_MODELINPUT = DESCRIPTOR.message_types_by_name['ModelInput']
_MODELOUTPUTMETADATA = DESCRIPTOR.message_types_by_name['ModelOutputMetadata']
_MODELOUTPUT = DESCRIPTOR.message_types_by_name['ModelOutput']
_INVOCATIONREQUEST = DESCRIPTOR.message_types_by_name['InvocationRequest']
_INVOCATIONRESPONSE = DESCRIPTOR.message_types_by_name['InvocationResponse']
ModelInputMetadata = _reflection.GeneratedProtocolMessageType('ModelInputMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUTMETADATA,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.ModelInputMetadata)
  })
_sym_db.RegisterMessage(ModelInputMetadata)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUT,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.ModelInput)
  })
_sym_db.RegisterMessage(ModelInput)

ModelOutputMetadata = _reflection.GeneratedProtocolMessageType('ModelOutputMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUTMETADATA,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.ModelOutputMetadata)
  })
_sym_db.RegisterMessage(ModelOutputMetadata)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUT,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.ModelOutput)
  })
_sym_db.RegisterMessage(ModelOutput)

InvocationRequest = _reflection.GeneratedProtocolMessageType('InvocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONREQUEST,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.InvocationRequest)
  })
_sym_db.RegisterMessage(InvocationRequest)

InvocationResponse = _reflection.GeneratedProtocolMessageType('InvocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONRESPONSE,
  '__module__' : 'invocation_pb2'
  # @@protoc_insertion_point(class_scope:invocation.v1.InvocationResponse)
  })
_sym_db.RegisterMessage(InvocationResponse)

_INVOCATION = DESCRIPTOR.services_by_name['Invocation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELINPUTMETADATA._serialized_start=35
  _MODELINPUTMETADATA._serialized_end=83
  _MODELINPUT._serialized_start=85
  _MODELINPUT._serialized_end=179
  _MODELOUTPUTMETADATA._serialized_start=181
  _MODELOUTPUTMETADATA._serialized_end=230
  _MODELOUTPUT._serialized_start=232
  _MODELOUTPUT._serialized_end=311
  _INVOCATIONREQUEST._serialized_start=313
  _INVOCATIONREQUEST._serialized_end=380
  _INVOCATIONRESPONSE._serialized_start=382
  _INVOCATIONRESPONSE._serialized_end=435
  _INVOCATION._serialized_start=437
  _INVOCATION._serialized_end=528
# @@protoc_insertion_point(module_scope)
